### ISSUE TITLE
关于ZHC首页“经典咏流传”的问题

### ISSUE THREAD

**Issue by MrZhang365** [Remelens/ZHC-vscode#1]
好家伙，ZHC首页的话可以说是经典咏流传了。  
> 本站由[雨云](https://www.rainyun.com/MjcxMTc=_)提供计算服务

咱就说这就是个插件，都用不上服务器… 建议删掉 ~~，或者改成ZhangChat由雨云提供计算服务~~  
我记得[IM客户端](https://im.chat.zhangsoft.link/)刚开始也写了这句话，后来我加入开发后就改了…  
论经典的力量

**Comment by Remelens** [comment]
草（）okok（）（）

**Comment by Remelens** [comment]
应该OK了
